### ISSUE TITLE
Last Exception received

### ISSUE THREAD

**Issue by abranon** [rootdarkarchon/OhGeeCD#2]
2022-05-18 22:01:59.830 -05:00 [ERR] [PLUGINM] Error disposing Oh gee, CD
System.ArgumentException: This window is not registered on this WindowSystem.
   at Dalamud.Interface.Windowing.WindowSystem.RemoveWindow(Window window) in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\WindowSystem.cs:line 82
   at OhGeeCD.Plugin.Dispose() in C:\Users\darkarchon\source\repos\Oh gee CD\Oh gee CD\Plugin.cs:line 69
   at Dalamud.Plugin.Internal.Types.LocalPlugin.Dispose() in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 211
   at Dalamud.Plugin.Internal.PluginManager.Dispose() in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 207
2022-05-18 22:01:59.830 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNS0xOFQyMjowMTo1OS44MzA4MDcyLTA1OjAwIiwiSW5mbyI6IlN5c3RlbS5Bcmd1bWVudEV4Y2VwdGlvbjogVGhpcyB3aW5kb3cgaXMgbm90IHJlZ2lzdGVyZWQgb24gdGhpcyBXaW5kb3dTeXN0ZW0uXHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLldpbmRvd2luZy5XaW5kb3dTeXN0ZW0uUmVtb3ZlV2luZG93KFdpbmRvdyB3aW5kb3cpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXEludGVyZmFjZVxcV2luZG93aW5nXFxXaW5kb3dTeXN0ZW0uY3M6bGluZSA4MlxyXG4gICBhdCBPaEdlZUNELlBsdWdpbi5EaXNwb3NlKCkgaW4gQzpcXFVzZXJzXFxkYXJrYXJjaG9uXFxzb3VyY2VcXHJlcG9zXFxPaCBnZWUgQ0RcXE9oIGdlZSBDRFxcUGx1Z2luLmNzOmxpbmUgNjlcclxuICAgYXQgRGFsYW11ZC5QbHVnaW4uSW50ZXJuYWwuVHlwZXMuTG9jYWxQbHVnaW4uRGlzcG9zZSgpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFBsdWdpblxcSW50ZXJuYWxcXFR5cGVzXFxMb2NhbFBsdWdpbi5jczpsaW5lIDIxMVxyXG4gICBhdCBEYWxhbXVkLlBsdWdpbi5JbnRlcm5hbC5QbHVnaW5NYW5hZ2VyLkRpc3Bvc2UoKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxQbHVnaW5cXEludGVybmFsXFxQbHVnaW5NYW5hZ2VyLmNzOmxpbmUgMjA3IiwiQ29udGV4dCI6IltQTFVHSU5NXSBFcnJvciBkaXNwb3NpbmcgT2ggZ2VlLCBDRCJ9

-- Let me know if you need/want any additional files! For reference I was setting up what I wanted tracked for Astro and the plugin crashed.

**Comment by rootdarkarchon** [comment]
Can you tell me if this is on unloading the plugin or when did this exactly happen? Trying to figure out why this is an issue.

**Comment by rootdarkarchon** [comment]
Okay I fixed the issue that is visible in that log. But I am not sure why the plugin crashed, for that I need more detailed information.

**Comment by abranon** [comment]
Hi, I recreated my steps and didn't crash so I assume the patch worked, it would've been in I assume the initial loading of the plugin as I had only just installed it. If I get another last exception I'll send you the entirety of my log so you can close this issue 😄
